<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\Fonts\*.ttf" />
    <AvaloniaResource Include="Assets\icon-1024.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Feuerwehr.AppLogic\Feuerwehr.AppLogic.csproj" />
  </ItemGroup>

</Project>
