using System.Reflection;

namespace LageBuch.Documents;

/// <summary>
/// Brand artwork baked into the report. The mark ships as an embedded resource rather than a
/// file on disk so this project keeps its filesystem-free contract (see <see cref="IncidentPdf"/>,
/// whose callers hand in every other image as bytes) and so <see cref="IncidentPdf.Generate"/>
/// needs no extra parameter that every caller would have to thread through.
/// </summary>
public static class Branding
{
    private const string MarkResourceName = "LageBuch.Documents.Assets.lagebuch-mark.png";

    private static readonly Lazy<byte[]> LazyMark = new(LoadMark, isThreadSafe: true);

    /// <summary>
    /// The text-free Lagebuch emblem (helmet, flame, shield) as PNG bytes, on its dark disc —
    /// the disc is deliberate, since the helmet is white and would vanish on a white page.
    /// A method rather than a property (CA1819): the bytes are handed straight to QuestPDF's
    /// <c>Image</c>, and the same cached array is returned every time.
    /// </summary>
    public static byte[] GetMark() => LazyMark.Value;

    private static byte[] LoadMark()
    {
        using var stream = typeof(Branding).GetTypeInfo().Assembly
            .GetManifestResourceStream(MarkResourceName)
            ?? throw new InvalidOperationException(
                $"Embedded brand mark '{MarkResourceName}' is missing. It is declared as an " +
                "EmbeddedResource in LageBuch.Documents.csproj and generated by " +
                "packaging/logo/build-logo-assets.sh.");

        using var buffer = new MemoryStream();
        stream.CopyTo(buffer);
        return buffer.ToArray();
    }
}
