<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\Fonts\*.ttf" />
    <AvaloniaResource Include="Assets\icon-1024.png" />
    <AvaloniaResource Include="Assets\codeforfire.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LageBuch.AppLogic\LageBuch.AppLogic.csproj" />
  </ItemGroup>

</Project>
