<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LageBuch.Domain\LageBuch.Domain.csproj" />
    <ProjectReference Include="..\LageBuch.Sync\LageBuch.Sync.csproj" />
    <ProjectReference Include="..\LageBuch.Persistence\LageBuch.Persistence.csproj" />
    <ProjectReference Include="..\LageBuch.Documents\LageBuch.Documents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LageBuch.AppLogic.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
